language: c
compiler:
  - gcc
  - clang

before_script:
  #installing libsodium, needed for Core
  - git clone git://github.com/jedisct1/libsodium.git > /dev/null
  - cd libsodium
  - git checkout tags/0.4.2 > /dev/null
  - ./autogen.sh > /dev/null
  - ./configure --prefix=/usr > /dev/null
  - make check -j3 > /dev/null
  - sudo make install >/dev/null
  - cd ..
  #installing yasm, needed for compiling vpx
  - sudo apt-get install yasm > /dev/null
  #installing libopus, needed for audio encoding/decoding
  - wget http://downloads.xiph.org/releases/opus/opus-1.0.3.tar.gz > /dev/null
  - tar xzf opus-1.0.3.tar.gz > /dev/null
  - cd opus-1.0.3
  - ./configure --prefix=/usr > /dev/null
  - make -j3 > /dev/null
  - sudo make install > /dev/null
  - cd ..
  #installing vpx
  - git clone http://git.chromium.org/webm/libvpx.git > /dev/null
  - cd libvpx
  - ./configure --enable-shared --prefix=/usr > /dev/null
  - make -j3 >/dev/null
  - sudo make install > /dev/null
  - cd ..
  #creating libraries links and updating cache
  - sudo ldconfig > /dev/null
  
  - sudo ldconfig
  - git clone https://github.com/irungentoo/ProjectTox-Core.git toxcore
  - cd toxcore
  - autoreconf -i
  - ./configure --prefix=/usr --disable-tests --disable-ntox --disable-daemon --enable-av
  - make -j2
  - sudo make install
  - cd ..
  - sudo apt-get install libopenal-dev -yq
script:
  - ./configure --prefix=/usr
  - make depend all
notifications:
  email: false

  irc: 
    channels:
      - "chat.freenode.net#tox-dev"
    on_success: always
    on_failure: always
